name: ArmorTrimEdit
main: at.vailan.armortrimedit.ArmorTrimEdit
version: '2.1.0'
api-version: '1.21'
description: Allows players to edit Armor Trims
author: vailan

commands:
  armortrimedit:
    description: Opens the Armor Trim Editor GUI
    usage: /armortrimedit
    aliases:
      - armortrim
      - ae

permissions:
  armortrimedit.*:
    description: Gives access to all ArmorTrimEdit features
    children:
      - armortrimedit.use
      - armortrimedit.apply
      - armortrimedit.remove
    default: op

  armortrimedit.admin:
    description: Gives access to all ArmorTrimEdit features
    children:
      - armortrimedit.use
      - armortrimedit.apply
      - armortrimedit.remove
    default: op

  armortrimedit.use:
    description: Allows opening & using the Armor Trim Editor GUI
    children:
      - armortrimedit.apply
      - armortrimedit.remove
    default: true

  armortrimedit.apply:
    description: Allows adding Armor Trims to items
    default: true

  armortrimedit.remove:
    description: Allows removing Armor Trims from items
    default: true